version: '3'
services:
  unbundling-ee:
    container_name: unbundling-ee-container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/workspace
    command: sleep infinity
